set_shift:
  target:
    entity:
      integration: dienstplan
      domain: calendar
  fields:
    date:
      required: true
      example: "2026-10-05"
      selector:
        date:
    end_date:
      required: false
      example: "2026-10-09"
      selector:
        date:
    shift:
      required: false
      example: "F1"
      selector:
        text:

set_shifts:
  target:
    entity:
      integration: dienstplan
      domain: calendar
  fields:
    days:
      required: true
      example: '{"2026-10-05": "F1", "2026-10-06": "F1", "2026-10-07": "X"}'
      selector:
        object:

sync:
  target:
    entity:
      integration: dienstplan
      domain: calendar

regenerate_link:
  target:
    entity:
      integration: dienstplan
      domain: calendar
